const fs = require('fs');
const path = require('path');

const dataDir = 'e:/Small Projects/UEModManager/data/game';

const games = {
    'StellarBlade': {
        displayName: 'StellarBlade',
        nexusUrl: 'https://www.nexusmods.com/stellarblade/mods/',
        features: {
            clothingList: true
        },
        uiConfig: {
            windowTitle: 'StellarBlade Mod Manager',
            launchButtonText: '启动游戏',
            gamePathLabel: 'StellarBlade 游戏根目录:'
        },
        nameLookupData: [
            { en: 'Air Ace', cn: '天骄王牌' },
            { en: 'Angelic Rose', cn: '天使玫瑰' },
            { en: 'Aqua Pearl', cn: '水珍珠' },
            { en: 'Autonetic Bondage', cn: '自动绑带装' },
            { en: 'Black Full Dress', cn: '黑礼服' },
            { en: 'Black Kunoichi', cn: '墨黑忍者装' },
            { en: 'Black Lotus', cn: '乌莲' },
            { en: 'Black Pearl', cn: '黑珍珠' },
            { en: 'Black Rose', cn: '黑玫瑰' },
            { en: 'Black Wave', cn: '墨色波浪' },
            { en: 'Blue Monsoon', cn: '碧蓝季风' },
            { en: 'Comfort Force', cn: '舒适活力装' },
            { en: 'Comfort Knitted Dress', cn: '舒适针织裙装' },
            { en: 'Comfort Mascot', cn: '舒适吉祥物装' },
            { en: 'Comfort Sailor', cn: '舒适水手服' },
            { en: 'Cooling Suit', cn: '冷却服' },
            { en: 'Crew Style', cn: '空乘风' },
            { en: 'Crimson Wings', cn: '绯红之翼' },
            { en: 'Cyber Bunny', cn: '赛博兔女郎' },
            { en: 'Cyber Illusionist', cn: '赛博幻术师' },
            { en: 'Cyber Magician', cn: '赛博魔法师' },
            { en: 'Cyber Trickster', cn: '赛博诡术士' },
            { en: 'Cybernetic Bondage', cn: '赛博绑带装' },
            { en: 'Cybernetic Dress', cn: '赛博裙装' },
            { en: 'Cybernetic Suit', cn: '赛博服装' },
            { en: 'Daily Biker', cn: '休闲车手服' },
            { en: 'Daily Denim', cn: '牛仔布休闲装' },
            { en: 'Daily Force', cn: '休闲活力装' },
            { en: 'Daily Knitted Dress', cn: '休闲针织裙装' },
            { en: 'Daily Mascot', cn: '休闲吉祥物装' },
            { en: 'Daily Sailor', cn: '休闲水手服' },
            { en: 'Elegant Dress', cn: '优雅裙装' },
            { en: 'Elysion Combat Uniform', cn: '极乐净土战斗服' },
            { en: 'Emerald Passion', cn: '翡翠热情' },
            { en: 'Extreme Bunny', cn: '极致兔女郎' },
            { en: 'Fluffy Bear', cn: '毛绒熊熊' },
            { en: 'FourSeconds Biker', cn: '“四秒钟”车手服' },
            { en: 'FourSeconds Black Denim', cn: '“四秒钟”黑色牛仔布套装' },
            { en: 'FourSeconds Denim', cn: '“四秒钟”牛仔布套装' },
            { en: 'FourSeconds Destroyed Denim', cn: '“四秒钟”破洞牛仔布套装' },
            { en: 'FourSeconds Essential Wear', cn: '“四秒钟”基本造型' },
            { en: 'FourSeconds Everyday Wear', cn: '“四秒钟”休闲装' },
            { en: 'FourSeconds Striped Denim', cn: '“四秒钟”条纹牛仔布套装' },
            { en: 'Holiday Bunny', cn: '假日兔女郎' },
            { en: 'Holiday Rabbit', cn: '假日兔' },
            { en: 'Hydrangea', cn: '绣球花' },
            { en: 'Junk Engineer', cn: '废品工程师' },
            { en: 'Junk Mechanic', cn: '废料机械师' },
            { en: 'Keyhole Dress', cn: '镂空裙装' },
            { en: 'Keyhole Suit', cn: '镂空服' },
            { en: 'La Vie en Rose', cn: '玫瑰人生' },
            { en: 'Midsummer Alice', cn: '盛夏爱丽丝' },
            { en: 'Midsummer Redhood', cn: '盛夏小红帽' },
            { en: 'Missing Link', cn: '遗失之链' },
            { en: 'Motivation', cn: '动力十足' },
            { en: 'Moutan Peony', cn: '国色牡丹' },
            { en: 'Neurocircuit Bondage', cn: '神经元回路绑带装' },
            { en: 'Neurolink Skin', cn: '神经元链接紧身服' },
            { en: 'Neurolink Suit', cn: '神经元链接套装' },
            { en: 'Never Look Back', cn: '永不回头' },
            { en: 'Ocean Maid', cn: '海的女仆' },
            { en: 'Office Style', cn: '通勤装' },
            { en: 'Orca Engineer', cn: '奥卡工程师' },
            { en: 'Orca Exploration Suit', cn: '奥卡探索者' },
            { en: 'Orca Pathfinder', cn: '奥卡探路者' },
            { en: 'Orca Techie', cn: '奥卡技术员' },
            { en: 'Peony', cn: '芍药独韵' },
            { en: 'Photogenic', cn: '目光焦点' },
            { en: 'Pink Bear', cn: '粉红小熊' },
            { en: 'Planet Diving Protection Suit (7th)', cn: '星球空降防护服(第7小队)' },
            { en: 'Planet Diving Protection Suit (7th) V2', cn: '星球空降防护服(第7小队)第2版' },
            { en: 'Planet Diving Suit (2nd)', cn: '星球空降服(第2小队)' },
            { en: 'Planet Diving Suit (2nd) V2', cn: '星球空降服(第2小队)第2版' },
            { en: 'Planet Diving Suit (3rd)', cn: '星球空降服(第3小队)' },
            { en: 'Planet Diving Suit (3rd) V2', cn: '星球空降服(第3小队)第2版' },
            { en: 'Planet Diving Suit (5th)', cn: '星球空降服(第5小队)' },
            { en: 'Planet Diving Suit (6th)', cn: '星球空降服(第6小队)' },
            { en: 'Planet Diving Suit (6th) V2', cn: '星球空降服(第6小队)第2版' },
            { en: 'Planet Diving Suit (6th) V3', cn: '星球空降服(第6小队)第3版' },
            { en: 'Planet Diving Suit (7th)', cn: '星球空降服(第7小队)' },
            { en: 'Planet Diving Suit (7th) V2', cn: '星球空降服(第7小队)第2版' },
            { en: 'Planet Diving Suit (7th) V3', cn: '星球空降服(第7小队)第3版' },
            { en: 'Planet Diving Suit (Captain)', cn: '星球空降服(队长)' },
            { en: 'Prototype Neurolink Suit', cn: '神经元链接套装原型' },
            { en: 'Prototype Planet Diving Suit', cn: '星球空降服原型' },
            { en: 'Prototype Planet Diving Suit V2', cn: '星球空降服原型第2版' },
            { en: 'Prototype Sensate Suit', cn: '知觉套装原型' },
            { en: 'Punk Style', cn: '朋克风' },
            { en: 'Punk Top', cn: '朋克炸街服' },
            { en: "Racer's High", cn: '狂飙车手' },
            { en: 'Raven Suit', cn: '渡鸦装' },
            { en: 'Red Passion', cn: '赤血丹心' },
            { en: 'Red Pearl', cn: '赤色珍珠' },
            { en: 'Resonance', cn: '共鸣' },
            { en: 'Royal Guard Suit', cn: '神圣护卫套装' },
            { en: 'Santa Dress', cn: '圣诞裙装' },
            { en: 'Sensate Skin', cn: '知觉活肤紧身服' },
            { en: 'Shadow Kunoichi', cn: '暗影忍者装' },
            { en: 'Silver Kunoichi', cn: '亮银忍者装' },
            { en: 'Skin Suit', cn: '活肤紧身服' },
            { en: 'Sky Ace', cn: '空中王牌' },
            { en: "Speeder's High", cn: '极速快感' },
            { en: 'Sporty Energy', cn: '活力运动服' },
            { en: 'Sporty Yellow', cn: '黄色运动服' },
            { en: 'Stargazer Suit', cn: '占星服' },
            { en: 'Telegenic', cn: '丽影' },
            { en: 'Tidal Maid', cn: '海潮女仆' },
            { en: 'Ultimate Bunny', cn: '终极兔女郎' },
            { en: 'Wandering Swordfighter Outfit', cn: '浪游剑客服' },
            { en: 'War Aegis', cn: '烽火神盾' },
            { en: 'War Dress', cn: '烽火裙装' },
            { en: 'War Suit', cn: '烽火装' },
            { en: 'Wasteland Adventurer', cn: '废土冒险家' },
            { en: 'Wasteland Explorer', cn: '废土探索者' },
            { en: 'Wave Diver Bikini', cn: '“波浪”潜水比基尼' },
            { en: 'Wave Oblique Monokini', cn: '“波浪”斜款连体比基尼' },
            { en: 'White Full Dress', cn: '白礼服' },
            { en: 'White Kunoichi', cn: '洁白忍者装' },
            { en: 'White Monsoon', cn: '纯白季风' },
            { en: 'White Pearl', cn: '莹白珍珠' },
            { en: 'Wild Wave', cn: '怒涛' },
            { en: 'YoRHa No.2 Type B Uniform', cn: '寄叶二号B型制服' },
            { en: 'YoRHa Type A No.2 Uniform', cn: '寄叶A型二号制服' },
            { en: 'YoRHa Uniform 1', cn: '寄叶制服1' },
            { en: 'YoRHa Unofficial Ceremonial Attire', cn: '寄叶非正式礼仪着装' },
            { en: 'Ocean String', cn: '海洋之丝' }
        ]
    },
    'KCD2': {
        displayName: 'Kingdom Come: Deliverance 2',
        nexusUrl: 'https://www.nexusmods.com/kingdomcomedeliverance2',
        features: { clothingList: false },
        uiConfig: {
            windowTitle: 'KCD2 Mod Manager',
            launchButtonText: '启动游戏',
            gamePathLabel: 'KCD2 游戏根目录:'
        }
    },
    'RomancingSaGa2': {
        displayName: 'Romancing SaGa 2: Revenge of the Seven',
        nexusUrl: 'https://www.nexusmods.com/romancingsaga2revengeoftheseven',
        features: { clothingList: false },
        uiConfig: {
            windowTitle: 'RomancingSaGa2 Mod Manager',
            launchButtonText: '启动游戏',
            gamePathLabel: 'RomancingSaGa2 游戏根目录:'
        }
    }
};

Object.keys(games).forEach(id => {
    const filePath = path.join(dataDir, id + '.json');
    if (fs.existsSync(filePath)) {
        const fileData = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
        const updatedData = { ...fileData, ...games[id] };
        fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
        console.log('Updated ' + id + '.json');
    }
});
